import java.time.*
import java.time.format.DateTimeFormatter
pipeline {
    agent any
    stages {
        stage('Despliegue F2X') {
            steps {
               echo 'Desplegando en F2X'
            }
        }
        stage('Aprobacion manual') {
           input {
                message "Esta seguro que desea desplegar a F2X?"
                ok "Aprobar"
                parameters {
                   string(name: 'comentario', defaultValue: '', description: 'Deje aquí su comentario')
                }
            }
            steps {
                echo "${comentario}"
            }
        }
       stage('Configure and exec docker compose') {
            steps {
                sh "sudo docker-compose up -d --build && sudo docker image prune -f"
            }
        }
    }
}